<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Achu" failures="1" tests="5" name="testCases.CaResetPasswordTest" time="17.342" errors="0" timestamp="2023-10-26T17:47:45 BST" skipped="0">
  <testcase classname="testCases.CaResetPasswordTest" name="restPasswordCorrectDetail" time="7.443">
    <failure message="The following asserts failed:
	URL Mismatched expected [https://capital-analytical.myshopify.com/account/login] but found [https://capital-analytical.myshopify.com/account/login#recover]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
URL Mismatched expected [https://capital-analytical.myshopify.com/account/login] but found [https://capital-analytical.myshopify.com/account/login#recover]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at pages.CaResetPasswordPage.resetpassword(CaResetPasswordPage.java:59)
at testCases.CaResetPasswordTest.restPasswordCorrectDetail(CaResetPasswordTest.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- restPasswordCorrectDetail -->
  <testcase classname="testCases.CaResetPasswordTest" name="resetPasswordEmptyField" time="2.055"/>
  <testcase classname="testCases.CaResetPasswordTest" name="resetPasswordInvalid" time="3.834"/>
  <testcase classname="testCases.CaResetPasswordTest" name="resetPasswordCancelLink" time="3.051"/>
  <testcase classname="testCases.CaResetPasswordTest" name="resetPassInvalidEmailFor" time="0.959"/>
</testsuite> <!-- testCases.CaResetPasswordTest -->
