<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Achu" failures="1" tests="7" name="testCases.CaLoginTest" time="38.955" errors="0" timestamp="2023-10-18T17:54:24 BST" skipped="0">
  <testcase classname="testCases.CaLoginTest" name="LoginFormValid" time="6.464"/>
  <testcase classname="testCases.CaLoginTest" name="InvalidloginInfo" time="5.094"/>
  <testcase classname="testCases.CaLoginTest" name="emptylogin" time="4.125"/>
  <testcase classname="testCases.CaLoginTest" name="ValiduserInvalidpass" time="5.317"/>
  <testcase classname="testCases.CaLoginTest" name="Invaliduservalidpass" time="5.383"/>
  <testcase classname="testCases.CaLoginTest" name="InactiveUsernameAndPassowrd" time="5.560"/>
  <testcase classname="testCases.CaLoginTest" name="loginAndBackTest" time="7.012">
    <failure message="The following asserts failed:
	URL Mismatch expected [https://capital-analytical.myshopify.com/account/login] but found [https://capital-analytical.myshopify.com/account?analytics_trace_id=e2988d8a-e69a-4c69-b0c6-312cdb231924]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
URL Mismatch expected [https://capital-analytical.myshopify.com/account/login] but found [https://capital-analytical.myshopify.com/account?analytics_trace_id=e2988d8a-e69a-4c69-b0c6-312cdb231924]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at pages.CaLoginPage.loginAndBack(CaLoginPage.java:176)
at testCases.CaLoginTest.loginAndBackTest(CaLoginTest.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginAndBackTest -->
</testsuite> <!-- testCases.CaLoginTest -->
